name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        
    - name: Build the Docker image
      run: docker build -t python-flask-app .
    - name: Push to DockerHub
      run: docker push $DOCKER_USERNAME/python-flask-app:1.0